20 2/server renewal admin
isc-exhibition/exhibition-web pull request #27
Opened 2021-03-16 03:32 UTC by vivapyk

admin signup, signin

2021-03-17 03:57 UTC, JSKeum commented on server/src/auth/admin.entitiy.ts
> +  test: string;
test는 지워주세요!

2021-03-17 03:57 UTC, JSKeum commented on server/src/auth/admin.entitiy.ts
> +  salt: string;
salt도 db에 들어가야 하나요?

2021-03-17 03:57 UTC, JSKeum commented on server/src/auth/auth.controller.ts
> +    return hash;
test는 지워주세요!

2021-03-17 03:57 UTC, JSKeum commented on server/src/auth/auth.module.ts
> +      },
시간 관련 표현은 가독성 좋게 `60 * 60` 또는 변수를 사용할 수 있는 경우에는 `const 변수 = 60 * 60` 이런식으로 하는게 좋을 것 같습니다!
https://github.com/ryanmcdermott/clean-code-javascript#use-searchable-names

2021-03-17 03:57 UTC, JSKeum commented on server/src/auth/auth.service.ts
> +    return { accessToken };
accessToken을 response header로 담는게 좋을 것 같습니다!

2021-03-17 04:01 UTC, JSKeum commented
conflict는 좀더 수정한 다음에 합시다!

2021-03-17 10:49 UTC, vivapyk commented on server/src/auth/admin.entitiy.ts
> +  salt: string;
유저마다 고유 salt 값는 구조라 들어가야합니닷!

2021-03-17 10:50 UTC, vivapyk commented on server/src/auth/auth.service.ts
> +    return { accessToken };
response header로 담는 방법이 따로 있나요?

2021-03-17 11:00 UTC, vivapyk commented on server/src/auth/admin.entitiy.ts
> +  test: string;
넵

2021-03-17 11:00 UTC, vivapyk commented on server/src/auth/auth.controller.ts
> +    return hash;
넵!

2021-03-17 11:01 UTC, vivapyk commented on server/src/auth/auth.module.ts
> +      },
넵!

2021-03-17 13:44 UTC, JSKeum commented on server/src/auth/auth.service.ts
> +    return { accessToken };
정확히 말하면 jwt를 cookie에 저장하면 좋을 것 같고, set cookie 를 header에 담으면 좋을 것 같아요!

JWT를 어디에 저장해야 할 것인가?!
https://medium.com/@ryanchenkie_40935/react-authentication-how-to-store-jwt-in-a-cookie-346519310e81

2021-03-18 06:37 UTC, JSKeum requested changes

2021-03-18 06:37 UTC, JSKeum commented on server/src/auth/auth.module.ts
> +      secret: 'iscexhibition',
secret은 secret.json(gitignore에 추가해야 합니다) 에 담아 Import하는 방식으로 바꾸고, 값도 복잡한 걸로 바꿔주세요!

2021-03-19 15:58 UTC, JSKeum commented on server/src/auth/auth.module.ts
> +      secret: 'iscexhibition',
아니 secret.json 말고 aws Secret Manager 방식으로 해주세요!

2021-03-23 05:30 UTC, JSKeum commented on server/src/auth/admin.entitiy.ts
> +  }
isAdmin 속성으로 관리자를 정의하고 있으니, 엔티티의 이름을 Admin이 아니라 User로 하는게 맞지 않을까요?

2021-03-25 10:08 UTC, closed without merging