:sparkles: add getEventLetterAnswer api
isc-exhibition/exhibition-web pull request #28
Opened 2021-03-17 16:07 UTC by 9ummy

마구마구 봐주세요!

2021-03-17 16:14 UTC, JSKeum requested changes

2021-03-17 16:14 UTC, JSKeum commented on server/src/assignment/service/assignment.service.ts
> +    // }
요 주석은 그냥 지워주세요ㅎㅎ

2021-03-17 16:14 UTC, JSKeum commented
좋아요!

2021-03-18 15:58 UTC, 9ummy commented on server/src/assignment/service/assignment.service.ts
> +    // }
여기 주석 전체요?!

2021-03-19 02:30 UTC, JSKeum commented on server/src/assignment/service/assignment.service.ts
> +    // }
네 쓰지 않는 코드는 그냥 지워버립시다ㅋㅋㅋ

2021-03-19 02:56 UTC, JSKeum approved these changes

2021-03-19 14:11 UTC, merged